import type { CEFRWord } from './cefrData';

export const A1_SECTION_1: Record<string, CEFRWord> = {
  'a / an': {
    level: 'A1',
    pos: 'indefinite article',
    example: 'I have a cat.',
    exampleTurkish: 'Bir kedim var.',
    definition: 'Used before a singular noun to mean "one, any".',
    turkishMeaning: 'bir (belirsiz tanımlık)',
  },
  'about': {
    level: 'A1',
    pos: 'prep., adv.',
    example: 'We are talking about our holiday.',
    exampleTurkish: 'Tatilimiz hakkında konuşuyoruz.',
    definition: 'Concerning something; around a place or time.',
    turkishMeaning: 'hakkında; yaklaşık, civarında',
  },
  'above': {
    level: 'A1',
    pos: 'prep., adv.',
    example: 'The picture is above the sofa.',
    exampleTurkish: 'Resim kanepenin üzerindedir.',
    definition: 'In a higher place than something.',
    turkishMeaning: 'üzerinde, yukarısında',
  },
  'across': {
    level: 'A1',
    pos: 'prep., adv.',
    example: 'She walked across the street.',
    exampleTurkish: 'O, caddenin karşısına yürüdü.',
    definition: 'From one side to the other side.',
    turkishMeaning: 'karşıya, bir yandan öteki yana',
  },
  'action': {
    level: 'A1',
    pos: 'noun',
    example: 'The film has a lot of action.',
    exampleTurkish: 'Filmde çok fazla aksiyon var.',
    definition: 'Things that happen, especially exciting events.',
    turkishMeaning: 'aksiyon, hareket',
  },
  'activity': {
    level: 'A1',
    pos: 'noun',
    example: 'Reading is my favourite activity.',
    exampleTurkish: 'Okumak en sevdiğim etkinliktir.',
    definition: 'Something that you do for a purpose or for fun.',
    turkishMeaning: 'etkinlik, faaliyet',
  },
  'actor': {
    level: 'A1',
    pos: 'noun',
    example: 'He is a famous actor.',
    exampleTurkish: 'O, ünlü bir aktör.',
    definition: 'A man who acts in films, TV, or theatre.',
    turkishMeaning: 'erkek oyuncu, aktör',
  },
  'actress': {
    level: 'A1',
    pos: 'noun',
    example: 'The actress won an award.',
    exampleTurkish: 'Aktris bir ödül kazandı.',
    definition: 'A woman who acts in films, TV, or theatre.',
    turkishMeaning: 'kadın oyuncu, aktris',
  },
  'add': {
    level: 'A1',
    pos: 'verb',
    example: 'Add some sugar to the coffee.',
    exampleTurkish: 'Kahveye biraz şeker ekle.',
    definition: 'To put something more with something else.',
    turkishMeaning: 'eklemek, ilave etmek',
  },
  'address': {
    level: 'A1',
    pos: 'noun',
    example: 'What is your home address?',
    exampleTurkish: 'Ev adresin nedir?',
    definition: 'The details of where someone lives or works.',
    turkishMeaning: 'adres',
  },
  'adult': {
    level: 'A1',
    pos: 'noun',
    example: 'The film is only for adults.',
    exampleTurkish: 'Film sadece yetişkinler içindir.',
    definition: 'A person who is fully grown.',
    turkishMeaning: 'yetişkin',
  },
  'advice': {
    level: 'A1',
    pos: 'noun',
    example: 'He gave me good advice.',
    exampleTurkish: 'Bana iyi tavsiyeler verdi.',
    definition: 'Suggestions about what you should do.',
    turkishMeaning: 'tavsiye, öğüt',
  },
  'afraid': {
    level: 'A1',
    pos: 'adj.',
    example: 'She is afraid of dogs.',
    exampleTurkish: 'Köpeklerden korkuyor.',
    definition: 'Feeling fear, scared.',
    turkishMeaning: 'korkmuş, korkan',
  },
  'after': {
    level: 'A1',
    pos: 'prep.',
    example: 'We will eat after the movie.',
    exampleTurkish: 'Filmden sonra yemek yiyeceğiz.',
    definition: 'Later than something in time.',
    turkishMeaning: '-den sonra',
  },
  'afternoon': {
    level: 'A1',
    pos: 'noun',
    example: 'I usually study in the afternoon.',
    exampleTurkish: 'Genellikle öğleden sonra ders çalışırım.',
    definition: 'The time between 12:00 and evening.',
    turkishMeaning: 'öğleden sonra',
  },
  'again': {
    level: 'A1',
    pos: 'adv.',
    example: 'Please say it again.',
    exampleTurkish: 'Lütfen bunu tekrar söyle.',
    definition: 'One more time.',
    turkishMeaning: 'tekrar, yine',
  },
  'age': {
    level: 'A1',
    pos: 'noun',
    example: 'What is your age?',
    exampleTurkish: 'Yaşın kaç?',
    definition: 'The number of years someone has lived.',
    turkishMeaning: 'yaş',
  },
  'age_adv': { // handled renamed key if needed but 'age' is noun here
    level: 'A1',
    pos: 'adv.',
    example: 'I moved here two years ago.',
    exampleTurkish: 'Buraya iki yıl önce taşındım.',
    definition: 'Earlier than now in the past.',
    turkishMeaning: 'önce',
    word: 'ago' // will handle in context
  },
  'ago': {
    level: 'A1',
    pos: 'adv.',
    example: 'I moved here two years ago.',
    exampleTurkish: 'Buraya iki yıl önce taşındım.',
    definition: 'Earlier than now in the past.',
    turkishMeaning: 'önce',
  },
  'agree': {
    level: 'A1',
    pos: 'verb',
    example: 'I agree with your idea.',
    exampleTurkish: 'Fikrine katılıyorum.',
    definition: 'To have the same opinion as someone.',
    turkishMeaning: 'aynı fikirde olmak, katılmak',
  },
  'air': {
    level: 'A1',
    pos: 'noun',
    example: 'I opened the window for some fresh air.',
    exampleTurkish: 'Biraz temiz hava için pencereyi açtım.',
    definition: 'The mixture of gases we breathe.',
    turkishMeaning: 'hava',
  },
  'airport': {
    level: 'A1',
    pos: 'noun',
    example: 'We arrived at the airport early.',
    exampleTurkish: 'Havaalanına erken vardık.',
    definition: 'A place where planes take off and land.',
    turkishMeaning: 'havaalanı',
  },
  'all': {
    level: 'A1',
    pos: 'det., pron.',
    example: 'All students must take the test.',
    exampleTurkish: 'Tüm öğrenciler sınava girmek zorunda.',
    definition: 'Every person or thing in a group.',
    turkishMeaning: 'tüm, hepsi',
  },
  'also': {
    level: 'A1',
    pos: 'adv.',
    example: 'She speaks English and also French.',
    exampleTurkish: 'İngilizce konuşuyor, ayrıca Fransızca da konuşuyor.',
    definition: 'In addition; too.',
    turkishMeaning: 'ayrıca, aynı zamanda',
  },
  'always': {
    level: 'A1',
    pos: 'adv.',
    example: 'He is always late.',
    exampleTurkish: 'O her zaman geç kalır.',
    definition: 'At all times; every time.',
    turkishMeaning: 'her zaman',
  },
  'amazing': {
    level: 'A1',
    pos: 'adj.',
    example: 'The view from the hill is amazing.',
    exampleTurkish: 'Tepeden manzara harika.',
    definition: 'Very surprising or very good.',
    turkishMeaning: 'şaşırtıcı, harika',
  },
  'and': {
    level: 'A1',
    pos: 'conj.',
    example: 'I like tea and coffee.',
    exampleTurkish: 'Çay ve kahveyi severim.',
    definition: 'Used to join words or sentences.',
    turkishMeaning: 've',
  },
  'angry': {
    level: 'A1',
    pos: 'adj.',
    example: 'She was angry with me.',
    exampleTurkish: 'Bana kızgındı.',
    definition: 'Feeling strong dislike because of something bad.',
    turkishMeaning: 'kızgın',
  },
  'animal': {
    level: 'A1',
    pos: 'noun',
    example: 'The elephant is a big animal.',
    exampleTurkish: 'Fil büyük bir hayvandır.',
    definition: 'A living creature that is not a plant or a person.',
    turkishMeaning: 'hayvan',
  },
};
